jupyterhub:
  ingress:
    hosts: [lacc.cloudbank.2i2c.cloud]
    tls:
      - hosts: [lacc.cloudbank.2i2c.cloud]
        secretName: https-auto-tls
  custom:
    2i2c:
      add_staff_user_ids_to_admin_users: true
      add_staff_user_ids_of_type: "google"
    homepage:
      templateVars:
        org:
          name: Los Angeles City College
          logo_url: https://www.lacitycollege.edu/sites/lacc.edu/files/lacc-logo.svg
          url: https://www.lacitycollege.edu/
        designed_by:
          name: 2i2c
          url: https://2i2c.org
        operated_by:
          name: CloudBank
          url: http://cloudbank.org/
        funded_by:
          name: CloudBank
          url: http://cloudbank.org/
  hub:
    config:
      JupyterHub:
        authenticator_class: cilogon
      CILogonOAuthenticator:
        oauth_callback_url: "https://lacc.cloudbank.2i2c.cloud/hub/oauth_callback"
        allowed_idps:
          http://google.com/accounts/o8/id:
            username_derivation:
              username_claim: "email"
          urn:mace:incommon:berkeley.edu:
            username_derivation:
              username_claim: "email"
      Authenticator:
        # FIXME: In z2jh 3.0.0-beta.1, a truthy allowed_users implies
        #        allow_existing_users=True, while in z3jh 3.0.0 this needs to be
        #        configured explicitly.
        #
        allowed_users: &lacc_users
          - PINEDAEM@laccd.edu
          - LAMKT@laccd.edu
          - ericvd@berkeley.edu
          - k_usovich@berkeley.edu
          - sean.smorris@berkeley.edu
        admin_users: *lacc_users
