jupyterhub:
  ingress:
    hosts: [palomar.cloudbank.2i2c.cloud]
    tls:
      - hosts: [palomar.cloudbank.2i2c.cloud]
        secretName: https-auto-tls
  custom:
    2i2c:
      add_staff_user_ids_to_admin_users: true
      add_staff_user_ids_of_type: "google"
    homepage:
      templateVars:
        org:
          name: Palomar Community College
          logo_url: https://www2.palomar.edu/pages/guidelines/files/2016/03/webGuide_screened_2-color_light.jpg
          url: https://www2.palomar.edu/
        designed_by:
          name: 2i2c
          url: https://2i2c.org
        operated_by:
          name: CloudBank
          url: http://cloudbank.org/
        funded_by:
          name: CloudBank
          url: http://cloudbank.org/
  hub:
    config:
      JupyterHub:
        authenticator_class: cilogon
      CILogonOAuthenticator:
        oauth_callback_url: "https://palomar.cloudbank.2i2c.cloud/hub/oauth_callback"
        allowed_idps:
          http://google.com/accounts/o8/id:
            username_derivation:
              username_claim: "email"
          urn:mace:incommon:berkeley.edu:
            username_derivation:
              username_claim: "email"
      Authenticator:
        # FIXME: In z2jh 3.0.0-beta.1, a truthy allowed_users implies
        #        allow_existing_users=True, while in z3jh 3.0.0 this needs to be
        #        configured explicitly.
        #
        allowed_users: &palomar_users
          - aculich@berkeley.edu
          - sean.smorris@berkeley.edu
          - tcanon@palomar.edu
          - PChen@palomar.edu
        admin_users: *palomar_users
